### ISSUE TITLE
ttt_juggernautsuit_*_loadout ConVars causing errors on load

### ISSUE THREAD

**Issue by Malivil** [Zaratusa/ttt-juggernaut-suit#1]
> [[TTT] Juggernaut Suit (Passive Perk)] gamemodes/terrortown/entities/entities/ttt_juggernaut_suit/shared.lua:22: attempt to index a nil value
>   1. unknown - gamemodes/terrortown/entities/entities/ttt_juggernaut_suit/shared.lua:22
>    2. include - [C]:-1
>     3. unknown - gamemodes/terrortown/entities/entities/ttt_juggernaut_suit/init.lua:16

It looks like you removed the loadout ConVars but didn't update/remove the usage of them in shared.lua

**Comment by Zaratusa** [comment]
It didn't remove the ConVars, but the min & max values seem to cause the bugs...

**Comment by Malivil** [comment]
Oh, I see they are in init.lua. I was just looking in shared.lua.

**Comment by Malivil** [comment]
That error is still occurring with the latest version
